### ISSUE TITLE
Help with organizing notebooks...

### ISSUE THREAD

**Issue by tsizzle** [AlJohri/DAT-DC-12#1]
Hi Al, during the course you asked if someone could assist with helping to organize the notebooks from DAT-DC-12 (can happen after the course ends)... I replied that I might be able to assist and I'd like to see if I can make good on that promise. I figure it'll be a good opportunity for me to review what we talked about in class and help me get more familiar with GitHub and its workflows.  Since, I'm still a newbie to GitHub, apologize in advance for if I'm unfamiliar with certain etiquettes or how to do things properly.

**Comment by AlJohri** [comment]
Let's do it. Find some specific thing you want to tackle, a particular topic, or organizational fix perhaps, and open an issue for it. We'll talk about it in that issue. Thanks Tony!
